# 3D-Printed Adjustable Fixture for Precision Glass Cutting (v3 & v4)

**Author:** Ashot Tumaghyan  
**Affiliation:** Materials Chemistry, University of Texas at Austin  
**Contact:** [ashottumaghyan30@gmail.com](mailto:ashottumaghyan30@gmail.com)

---

## Overview

Many scientific and artistic glass applications require tubing or components cut at precise, repeatable angles. This project delivers a low-cost, 3D-printable fixture—requiring only basic hardware and a sacrificial backplate—that anyone with a 3D printer can assemble.

Versions 3 and 4 improve upon earlier prototypes by offering angle locking mechanisms and fine-tuned linear adjustments, all while retaining high accuracy and precision.



## Bill of Materials

### Common to Both v3 & v4

- **Linear adjustment**  
  - 1× M6 × 1.0 mm hex-head screw  
  - 1× M6 × 1.0 mm 12-point flange nut  
- **Sacrificial backplate**  
  - ¼″ sheet (PP, PE, acrylic, etc.)

### Version 3 Only

- 4× M6 screws (hinge mounts, plastic heat insert/threaded plastic)  
- 1× M6 hex-head screw + 12-pt flange nut (linear)  
- 1× locking hinge  
- 1× small calibration screw  

### Version 4 Only

- 1× M6 screw + nut + PTFE washer + O-ring (lock)  
- 1× M6 hex-head screw + 12-pt flange nut (linear)  

Hardware can be sourced from McMaster-Carr; detailed part numbers available on request.

---

## 3D Printing & Materials

- **Filament:** PETG  
- **Layer height:** 0.20 mm  
- **Wall loops:** 4  
- **Infill:** 20% (increase wall/infill for extra durability)  
- **Orientation:** Minimize supports by printing with major flat faces on the build plate.

---

## Assembly & Use

1. **Print all plastic parts** for your chosen version.  
2. **Install hardware:**
   - Insert and heat-set M6 or thread plastic (v3) or assemble PTFE/O-ring lock (v4).  
   - Fix flange nut in its slot with a drop of adhesive.  
3. **Mount sacrificial backplate** behind the main fixture (might need to cut a piece to size).  
4. **Calibrate angle:**
   - v3: Adjust parallelism screw until both jaws align.  
   - v4: Align arrow with desired division mark (color-fill for visibility).  
5. **Lock angle**—thumb-tighten hinge (v3) or torque M6 lock screw (v4).  
6. **Adjust linear feed** for glass thickness: one revolution = 1 mm travel; each printed slot = 0.25 mm.

---

## Future Work & Acknowledgments

- **Tolerances:** Improve hinge alignment and reduce backlash.  
- **Customizations:** User-suggested modifications welcome—submit issues or mods!  
- **Thanks to** Adam Kennedy, Scientific Glassblower (UT Austin) for feedback and support.

---

## License

This project is released under the **MIT License**.

Project files are free to distribute; donations are welcome. Enjoy precise, accessible glass cutting!
